config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :posts, only: [:index, :destroy]
    resources :customers, only: [:index, :destroy]
  end
  scope module: :public do
    get  "homes/about"  => "homes#about"
    root :to => 'homes#top'
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'posts#search'
    get 'searching' => 'posts#searching'
    resources :customers, only: [:show, :edit, :update, :index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  enum gender: { man: 1, woman: 2 }
  
  attachment :profile_image
  validates :introduction, presence: false, length: { maximum: 50 }
  validates :nickname, presence: true, uniqueness: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def destroy
    @customer = Customer.find(params[:id])
    if @customer.destroy
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/posts_helper.rb
module Customer::PostsHelper
end

app/views/admin/customers/index.html.erb
<div>
  <h1>USERS</h1>
</div>
<%#会員一覧%>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>ニックネーム</th>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><td><%= attachment_image_tag(customer, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"40x40" ) %></td></td>
        <td><%= customer.nickname %></td>
        <td><%= customer.posts.count %></td>
        <td><%= link_to '削除', admin_customer_path(customer.id), method: :delete, class:"btn btn-danger btn-sm btn-block mb-3" %></td>
      </tr>
    <% end %>
  </tbody>
</table>