config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :posts, only: [:index, :destroy]
    resources :customers, only: [:index, :destroy]
  end
  scope module: :public do
    get  "homes/about"  => "homes#about"
    root :to => 'homes#top'
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'posts#search'
    get 'searching' => 'posts#searching'
    resources :customers, only: [:show, :edit, :update, :index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SUSHIP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "SUSHIP", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <%#会員のログイン時%>
          <% if customer_signed_in? %>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "HOME", root_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "ABOUT", homes_about_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "MY PAGE", customer_path(current_customer.id), class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "USERS", customers_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "POSTS", posts_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "NEW POST", new_post_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "LOG OUT", destroy_customer_session_path, class: "btn btn-sm btn-dark", method: :delete %>
          </li>
          <%#管理者のログイン時%>
          <% elsif admin_signed_in? %>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "HOME", root_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "ABOUT", homes_about_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "USERS", admin_customers_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "POSTS", admin_posts_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "LOG OUT", destroy_admin_session_path, class: "btn btn-sm btn-dark", method: :delete %>
          </li>
          <%#未ログイン時%>
          <% else %>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "HOME", root_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "ABOUT", homes_about_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "SIGN UP", new_customer_registration_path, class: "btn btn-sm btn-dark" %>
          </li>
          <li class="nav-item" style="margin-right: 50px;">
            <%= link_to "LOG IN", new_customer_session_path, class: "btn btn-sm btn-dark" %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>